version: "3"
services:
  stellanova_readingpost:
    image: readingpost:latest
    ports:
      - "9003:9003"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stellanova?autoReconnect=true&useSSL=false
      - spring.application.name=reading-service
      - server.port=9003
      - eureka.client.service-url.default-zone=http://stellanova_eureka:8761
    networks:
      - springmysql-net
    links:
      - stellanova_eureka
    depends_on:
      - mysqldb

  stellanova_eureka:
    image: eureka:latest
    ports:
      - "8761:8761"
    networks:
      - springmysql-net
    environment:
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - server.port=8761
      - eureka.hostname=stellanova_eureka
      - eureka.client.service-url.default-zone=http://stellanova_eureka:8761

  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - springmysql-net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stellanova

networks:
  springmysql-net: