apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reading-service
  name: reading-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reading-service
  strategy: {}
  template:
    metadata:

      labels:
        app: reading-service
    spec:
      containers:
        - env:
            - name: spring.datasource.url
              value: "jdbc:mysql://mysql:3306/stellanova?autoReconnect=true&useSSL=false"

            - name: spring.datasource.driver-class-name
              value: "com.mysql.cj.jdbc.Driver"

            - name: spring.datasource.username
              value: "root"

            - name: spring.datasource.password
              value: ""
#
#            - name: spring.datasource.password
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-pass
#                  key: password

            - name: spring.jpa.show-sql
              value: "true"

            - name: spring.jpa.properties.hibernate.dialect
              value: "org.hibernate.dialect.MySQL5Dialect"

            - name: spring.jpa.hibernate.ddl-auto
              value: "update"

            - name: spring.jpa.properties.hibernate.format_sql
              value: "true"

            - name: spring.application.name
              value: "reading-service"

            - name: server.port
              value: "9003"

            - name: eureka.client.serviceUrl.defaultZone
              value: "http://10.100.85.18:8761/eureka"

            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

          image: 412344443/stellanova_reading:latest
          name: reading-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reading-service
  name: reading-service
spec:
  ports:
    - name: "9003"
      port: 9003
      targetPort: 9003
  selector:
    app: reading-service
status:
  loadBalancer: {}
